services:
  - type: web
    name: yoasobi-checker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: EMAIL_ADDRESS
        value: appy19911029@gmail.com
      - key: EMAIL_PASSWORD
        value: pqqv wuch ekdv cbjr
      - key: TO_EMAIL
        value: appy19911029@gmail.com

      

